app:
    resource: "@AppBundle/Resources/config/routing.yml"
    
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"  

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin